### ISSUE TITLE
Traceback during an analyzation run after successfully inspecting several segments

### ISSUE THREAD

**Issue by asciifaceman** [jeoliva/hls-analyzer#9]
```
***** Analyzing variant (1478083) *****

	** Generic information **
	Version: 3
	Start Media sequence: 279
	Is Live: True
	Encrypted: False
	Number of segments: 10
	Playlist duration: 60.06

	** Downloading https://redacted/playlist_768x432_1200k_00286.ts, Range: None **
	** Tracks and Media formats **
	Track #0 - Type: video/avc, Format: Video (H.264) - Profile: Main, Level: 64, Resolution: 768x432, Encoded aspect ratio: 1/1, Display aspect ratio: 16/9
	Track #1 - Type: audio/mp4a-latm, Format: Audio (AAC) - Sample Rate: 48000, Channels: 2
	Track #2 - Type: unknown, Format: Unknown
	Track #3 - Type: application/id3, Format: ID3

	** Timing information **
	Segment declared duration: 6.006
	Track #0 - Duration: 5.939267 s, First PTS: 1689.752733 s, Last PTS: 1695.692 s
	Track #1 - Duration: 5.973332 s, First PTS: 1689.756066 s, Last PTS: 1695.729398 s
	Track #2 - Duration: 0.0 s, First PTS: 0.0 s, Last PTS: 0.0 s
	Track #3 - Duration: 0.0 s, First PTS: 0.0 s, Last PTS: 0.0 s
	Duration difference (declared vs real): 0.066733s (1.12%)

	** Frames **
	Track #0 - Frames:  I P B B B P B B B P B B B P B B B P B B B P B B B P B B B P 	AA: 286, BB: 1478083

		Good! Track starts with a keyframe
		Keyframes count: 3
		Key frame interval within track: 2.002 seconds

	Track #1 - Frames:  I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I
	Track #2 - Frames:
	Track #3 - Frames:


Traceback (most recent call last):
  File "hls-analyzer.py", line 214, in <module>
    analyze_variants_frame_alignment()
  File "hls-analyzer.py", line 180, in analyze_variants_frame_alignment
    if vf.segmentsFirstFramePts[segment_index] != value:
KeyError: 285
```

**Comment by alexdej** [comment]
I just hit this issue trying to use this tool on a live stream with short segments (2s). The problem in my case appears to be that by the time the tool has downloaded the required number of segments  from the first variant playlist (as defined by the `-s` argument), the next playlist has a different starting media sequence number. 

** update **  After re-reading the code it looks like the sequence handling is correct so I deleted that part of my comment.
